apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hns-argo-test-app
  namespace: argocd-system
spec:
  destination:
    server: https://kubernetes.default.svc
  project: hns-argo-test
  source:
    path: ./app/
    repoURL: https://github.com/llarsson/hns-argo-test
    targetRevision: HEAD
  syncPolicy:
    automated:
    ⦙ prune: true
    ⦙ selfHeal: true
